# build environment
FROM node:12.2.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV COUNTRY_CODE=${COUNTRY_CODE}
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
COPY . /app
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /var/www/ts-app
RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY docker/certs/server.crt /etc/nginx/conf.d/server.crt
COPY docker/certs/server.key /etc/nginx/conf.d/server.key
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]