version: '3.7'

services:
    ts-app:
        container_name: ts-app
        build:
            context: .
            dockerfile: Dockerfile-prod
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '443:443'
        environment:
            NODE_ENV: production
            COUNTRY_CODE: ${COUNTRY_CODE}
            HTTPS: 'true'